name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.1  # Specify the Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./... -v

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build  # Build the services defined in docker-compose.yml

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push  # Push the images defined in docker-compose.yml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Decode and save Kubernetes certificates
        run: |
          echo "${{ secrets.BASE64_CLIENT_CERT }}" | base64 --decode > $HOME/.kube/client.crt
          echo "${{ secrets.BASE64_CLIENT_KEY }}" | base64 --decode > $HOME/.kube/client.key
          echo "${{ secrets.BASE64_CA_CERT }}" | base64 --decode > $HOME/.kube/ca.crt

      - name: Verify decoded certificates
        run: |
          ls -l $HOME/.kube/
          cat $HOME/.kube/client.crt
          cat $HOME/.kube/client.key
          cat $HOME/.kube/ca.crt

      - name: Write KUBE_CONFIG_DATA to config file
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: $HOME/.kube/config
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
